# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jwhaney
email:
description: > # this means to ignore newlines until "baseurl:"
  jwhaney's personal site with some projects and contact info. check it out if you're looking for me.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://jwhaney.github.io" # the base hostname & protocol for your site
# twitter_username: Taffye
# github_username:
# linkedin_username: jhaney

# Build settings
markdown: kramdown
kramdown:
  input: GFM

encoding: utf-8

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-86670127-1
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
