# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Haney
email: geojwh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  John W. Haney's personal website, blog, and portfolio. Check it out.
baseurl:  # the subpath of your site, e.g. /blog
url: "http://johnwhaney.com" # the base hostname & protocol for your site
# twitter_username: Taffye
# github_username:
# linkedin_username: jhaney

# Build settings
markdown: kramdown
kramdown:
  input: GFM

encoding: utf-8

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-86670127-1
disqus_shortname: johnwhaney

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
